"""add macro columns

Revision ID: 0f270f44ac5c
Revises: 6e4d1af65614
Create Date: 2026-08-17 22:17:58.462788

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "0f270f44ac5c"
down_revision: Union[str, Sequence[str], None] = "6e4d1af65614"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meals", sa.Column("calories", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "meals",
        sa.Column("protein_g", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "meals", sa.Column("carbs_g", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column(
        "meals", sa.Column("fats_g", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meals", "fats_g")
    op.drop_column("meals", "carbs_g")
    op.drop_column("meals", "protein_g")
    op.drop_column("meals", "calories")
    # ### end Alembic commands ###
