"""add_pantry_saved_plans_timing_and_ratings

Revision ID: 699ec9e1324f
Revises: 0f270f44ac5c
Create Date: 2026-08-17 22:51:25.082697

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "699ec9e1324f"
down_revision: Union[str, Sequence[str], None] = "0f270f44ac5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pantry_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("is_in_stock", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pantry_items_id"), "pantry_items", ["id"], unique=False)
    op.create_index(op.f("ix_pantry_items_name"), "pantry_items", ["name"], unique=True)
    op.create_table(
        "saved_plans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("plan_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_plans_id"), "saved_plans", ["id"], unique=False)
    op.add_column("meals", sa.Column("prep_time_mins", sa.Integer(), nullable=False))
    op.add_column("meals", sa.Column("cook_time_mins", sa.Integer(), nullable=False))
    op.add_column("meals", sa.Column("servings_default", sa.Integer(), nullable=False))
    op.add_column("meals", sa.Column("rating", sa.Float(), nullable=False))
    op.add_column("meals", sa.Column("ratings_count", sa.Integer(), nullable=False))
    op.add_column("meals", sa.Column("is_favorite", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meals", "is_favorite")
    op.drop_column("meals", "ratings_count")
    op.drop_column("meals", "rating")
    op.drop_column("meals", "servings_default")
    op.drop_column("meals", "cook_time_mins")
    op.drop_column("meals", "prep_time_mins")
    op.drop_index(op.f("ix_saved_plans_id"), table_name="saved_plans")
    op.drop_table("saved_plans")
    op.drop_index(op.f("ix_pantry_items_name"), table_name="pantry_items")
    op.drop_index(op.f("ix_pantry_items_id"), table_name="pantry_items")
    op.drop_table("pantry_items")
    # ### end Alembic commands ###
